### ISSUE TITLE
Test suites are not able to access/use the ISO schemas

### ISSUE THREAD

**Issue by fabiovin** [etf-validator/etf-webapp#198] opened 2019-04-18 15:14 UTC
### Description

Test suites are not able to access/use the ISO schemas (from the repository: http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas).
For instance, if in the metadata the following value - xsi:schemaLocation="http://www.isotc211.org/2005/gmx http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/gmx/gmx.xsd http://www.isotc211.org/2005/gmd http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/gmd/gmd.xsd - is declared, the schema validation fails. The same metadata successfully validates with XMLSpy.

Related discussion: inspire-eu-validation/ets-repository#244

### Steps to Reproduce

[Describe the exact steps which can be used to reproduce the problem]

1. Open the INSPIRE Validator and select the "Conformance class: Metadata for interoperability" under the Metadata Test suite.
2. Upload the attached xml file and validate it.

**Expected behavior:** Successfully schema validation (Schema validation: md-xml.a.1: valiadate XML documents).

**Actual behavior:** The dataset has 1 file(s) with errors for this assertion.
XML document 'OSOpenNames_iso_https.xml': The file has 2 schema validation error(s).
XML document 'OSOpenNames_iso_https.xml': -1:-1: Premature end of file.
XML document 'OSOpenNames_iso_https.xml': -1:-1: Premature end of file.

[OSOpenNames_iso.zip](https://github.com/etf-validator/etf-webapp/files/3095036/OSOpenNames_iso.zip)

**Comment by cportele** [comment] 2019-04-22 16:24
It is not an ETF issue. If I try to validate the XML file using Xerces-J on the command line or online at https://www.freeformatter.com/xml-validator-xsd.html I get the same error. That is, the issue is not specific to ETF and occurs in a number of schema validation contexts. I am, therefore, closing this issue here.

In any case, since the standard.iso.org server uses HSTS, I would use https-URIs for the schema references, not http-URIs. However, that is unlikely to solve the issue as the schema documents in the ISO schema repository use http-URIs themselves... Maybe ignore the ISO server and use the OGC schema repository.

**Closed by cportele** 2019-04-22 16:24 UTC
